### ISSUE TITLE
how you make the arch background transparent?

### ISSUE THREAD

**Issue by applemate** [szastupov/progress-arc-component#3]
hi, is it possible to make the background transparent?

And how would you change the thickness  of the circle?

**Comment by szastupov** [comment]
> hi, is it possible to make the background transparent?

hi! just create a new styled component based on progress-arc and define background color with css, see the second example at https://szastupov.github.io/progress-arc-component/

> And how would you change the thickness of the circle?

You cand do it with styled-components as well by redefining stroke-width:
```javascript
const ThinArc = styled(ProgressArc)`
  circle {
    stroke-width: 10;
  }
`
```
